[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "https://innovativemisbahtahir.com/*"
  to = "https://www.innovativemisbahtahir.com/:splat"
  status = 301
  force = true
